### ISSUE TITLE
ImportError: cannot import name 'reduce_op'

### ISSUE THREAD

**Issue by north-horse** [SsnL/dataset-distillation#12]
when i run the code 
 `python main.py --mode distill_basic --dataset MNIST --arch LeNet`
i got this 
`Traceback (most recent call last):
  File "F:\dataset_dis\dataset-distillation-master\utils\distributed.py", line 5, in <module>
    from torch.distributed import ReduceOp
ImportError: cannot import name 'ReduceOp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from base_options import options
  File "F:\dataset_dis\dataset-distillation-master\base_options.py", line 6, in <module>
    import utils
  File "F:\dataset_dis\dataset-distillation-master\utils\__init__.py", line 3, in <module>
    from . import distributed
  File "F:\dataset_dis\dataset-distillation-master\utils\distributed.py", line 7, in <module>
    from torch.distributed import reduce_op
ImportError: cannot import name 'reduce_op'`
is this because of the version of pytorch or something else?

**Comment by SsnL** [comment]
Yes this is because of your pytorch version. Make sure that you have 1.0.0 or later.

**Comment by north-horse** [comment]
> Yes this is because of your pytorch version. Make sure that you have 1.0.0 or later.

oh, i am so sorry that i see you reply now, thanks for you help, it works.

**Comment by xjwangsjtu** [comment]
<img width="687" alt="image" src="https://user-images.githubusercontent.com/23315065/56989322-24350e00-6b60-11e9-98f8-021350fc9150.png">
i am using torch 1.0.0 but this issue still occurs. Any clue on the problem? Thanks.

**Comment by SsnL** [comment]
@xjwangsjtu Fixed in https://github.com/SsnL/dataset-distillation/commit/ef46862bed45cb332389efbaa010cea4c84d7ccc
