### ISSUE TITLE
Getting what appears to be noise on Imagenette + XResnet

### ISSUE THREAD

**Issue by sshleifer** [SsnL/dataset-distillation#15]
I am getting outputs that look completely random when I try to run distillation on a subset of imagenet with a XResnet 18 model. 

I have only tried one set of command line args and was wondering whether you had any intuition for what I might obviously be doing wrong or had tried this before.

My command is: 
 
```
python main.py --mode distill_basic --dataset Imagenette --arch DXResNet18 --batch_size 64 \
    --distill_steps 3 --train_nets_type known_init --n_nets 1 \
    --test_nets_type same_as_train
```

I made my own `DXResnet18` class and Imagenette dataloader.

Thanks in advance!

**Comment by SsnL** [comment]
Fixed init should give you images that look like noise, as expected. :)

**Comment by sshleifer** [comment]
They look way worse than `teaser.png`. Were those created in a different way?

![image](https://user-images.githubusercontent.com/6045025/58219376-78df2b00-7cbf-11e9-83d4-238aeaca05a2.png)

**Comment by SsnL** [comment]
I wouldn't be surprised. You have a much larger network with a much larger image space. There could be a lot more ways of using high freq signals to overfit a particular init.

**Comment by sshleifer** [comment]
I cut to only 10 classes. Would you suggest also cutting to smaller images/smaller network?

**Comment by SsnL** [comment]
Number of classes doesn’t matter much. I do think lower res would help. However, these said, it is fixed init, so random noise looks normal to me.

**Comment by sshleifer** [comment]
It did! Thank you for being so responsive!

Is the code to train a model using the images in results.pth invoked by running with --phase test? 

I am trying to see whether can train good models on the distilled images with slightly different settings.

**Comment by SsnL** [comment]
> Is the code to train a model using the images in results.pth invoked by running with --phase test?

Yes. You can set different test lr settings, but for flexible and other hyperparameter tuning, you may want to implement your own :)

**Comment by SsnL** [comment]
I’m closing this one for now. Let me know if you need more help!
