### ISSUE TITLE
Does the instillation model and the test model must be the same?

### ISSUE THREAD

**Issue by ssxlconch** [SsnL/dataset-distillation#17]
Sorry for bothering, I have some question when reading the paper
I run main.py and it works well, my question is:
The first question:
Does the instillation model and the test model must be the same?
For example, if I got the distillation images using LeNet, can I train these images on AlexNet?
The second question:
Does the number of the distillation images must be equal to the class numbers?
For example, if I want to distillation the MNIST dataset, can I distillate it into 20 images?
(I saw the distillation_lables equals to num_class)

**Comment by SsnL** [comment]
> Does the instillation model and the test model must be the same? For example, if I got the distillation images using LeNet, can I train these images on AlexNet?

From our limited experiment on this, the images distilled on one architecture has some effects on others, but they train less effectively.

> Does the number of the distillation images must be equal to the class numbers? For example, if I want to distillation the MNIST dataset, can I distillate it into 20 images?

No it doesn't. You can change `distilled_images_per_class_per_step` to config that.

**Comment by SsnL** [comment]
I'm closing this one for now. Feel free to reopen should you have further questions!
