### ISSUE TITLE
Questions about implementation of optimizing distilled data

### ISSUE THREAD

**Issue by JWarlock** [SsnL/dataset-distillation#19]
Hello!

I am reading the source code, specifically ` class Trainer` in `train_distilled_image.py`. I have two questions regarding to your implementation of optimizing distilled data:

- When computing the gradient of final L w.r.t `w` in `params`,  you claim that you use `w `**(PRE-GD)** in paper and comment in the code.  But you are actually using weight **after** gd in line 156-160 in `train_distilled_image.py`, since `params` stores original model weight and model weights after gd in every step. In the loop (line 143), the `w` corresponds to model weight **POST-GD**, not **PRE-GD**. To verify my guess, I check that `len(params)=31`, `len(gws)=30` during running
`python main.py --mode distill_basic --dataset MNIST --arch LeNet`. That means in the loop, the updated model weight in the final step in first retrieved.
I guess simply disgarding the model weight after gd in the final step will do the job. 

- In line 172, you use `dw.add_(hvp_grad[0])` to update `dw`, which is wierd because gradient through different steps does not accumulate by adding. If `dw` denotes the gradient of final L w.r.t the updated `w` in each step, I wonder if `dw=(hvp_grad[0])` is the correct one. Because in my understanding, every unupdated model weight in this step is the updated model weight in last step, which makes `hvp_grad[0]` itself the gradient of final L w.r.t the updated `w` in each step.

Anyway, many thanks to your interesting works！

**Comment by SsnL** [comment]
Thank you for your detailed observations.

1. The `zip` in `for (data, label, lr), w, gw in reversed(list(zip(steps, params, gws)))` secretively discards the last `params[-1]` so each `w` should actually be before GD.

2. I think adding is correct. Since `w_t = w_{t-1} - gw{t-1}`, we have `dw_t = dw_{t-1} - dgw{t-1}`. Hence the addition.

Let me know if you have other questions and/or think that the above explanation is not satisfactory!

**Comment by JWarlock** [comment]
Thank you! I now see your code is correct. 

Just one more thing. As for question 2, since `w_t = w_{t-1} - gw{t-1}`, I think we have `\dL / \dw_{t-1} = \dL / \dw_{t} * [1 - \dgw_{t-1} / dw{t-1}] ` by the chain rule.  But still, the addition is correct

**Comment by SsnL** [comment]
Thanks again for your interest in this project! I'm closing this issue for now. Feel free to reopen should there be any other questions and/or comments.
