### ISSUE TITLE
Questions about training after dataset distillation

### ISSUE THREAD

**Issue by colorjam** [SsnL/dataset-distillation#21]
Hi, thank you for sharing your interesting work. 
I'm puzzled about how to train a network use the distilled data, does it just set `--mode` to 'train'  and keep other options unchanged. Such as 
`python main.py --mode train --dataset MNIST --arch LeNet \
    --distill_steps 1 --train_nets_type known_init --n_nets 1 \
    --test_nets_type same_as_train`

**Comment by SsnL** [comment]
The `train` mode trains networks in the normal way. For testing distilled data, please see https://github.com/SsnL/dataset-distillation/blob/master/docs/advanced.md.
