### ISSUE TITLE
Compare to training on randomly selected samples

### ISSUE THREAD

**Issue by bennyguo** [SsnL/dataset-distillation#27]
Do you guys try to compare the results of distilled data to the ones trained on randomly selected samples of the dataset?
For example, if I randomly select 10 images from the MNIST dataset (1 for each category) and train the network on them, how would the results be? I think it's a fundamental thing to compare with. 

Very interesting work by the way!

**Comment by SsnL** [comment]
This comparison is in the paper. Thanks for your interest in our work. :)

**Comment by bennyguo** [comment]
Oh I must have missed it. Thanks,
