### ISSUE TITLE
Cannot find definition of `local_n_nets`

### ISSUE THREAD

**Issue by XinDongol** [SsnL/dataset-distillation#32]
`state.local_n_nets` is used without definition. What's the meaning of it?

If `train_nets_type=='known_init'`, why we want to build several networks with **different** initialization?

https://github.com/SsnL/dataset-distillation/blob/24e6958cf23bc98de20a7b2714fc76fa7d38b874/main.py#L90-L91

Thanks a lot!

**Comment by XinDongol** [comment]
Any Update?

**Comment by SsnL** [comment]
It is set here https://github.com/SsnL/dataset-distillation/blob/24e6958cf23bc98de20a7b2714fc76fa7d38b874/base_options.py#L444

It means the number of training models in a single rank of distributed training. In case of no distributed training, it equals the total number of training models.

With `known_init`, `n_nets` controls the number of known initializations, i.e., whether you want to overfit for one model, or for multiple models.
