### ISSUE TITLE
Running in Jupyter

### ISSUE THREAD

**Issue by arefm** [SsnL/dataset-distillation#38]
Hi SsnL

I'm trying to run this on the Jupyter but it returns this error:
`Unexpected args: ['-f', '/home/user/.local/share/jupyter/runtime/kernel-d7f01d0e-54cb-461d-8d44-0d43cb505a17.json']`

I searched for it, it seems the jupyter can't pass arguments correctly to base_options.py
Do you have any idea that how can I fix it?

**Comment by SsnL** [comment]
Hi, we don’t test running on Jupyter so I can’t help you with that. Sorry!
