### ISSUE TITLE
How to use it for custom model and dataset?

### ISSUE THREAD

**Issue by Ebjderman** [SsnL/dataset-distillation#39]
Thank you for your nice work. 
Could you please provide an example about how to use it for distilling any custom dataset and employ user-defined network structure?

**Comment by SsnL** [comment]
It requires
1. modifying https://github.com/SsnL/dataset-distillation/blob/master/datasets/__init__.py to include your dataset
2. modifying https://github.com/SsnL/dataset-distillation/blob/master/networks/networks.py to include your network
3. add proper argparsing for building dataset and network

The linked files have a couple examples you can probably follow.

**Comment by Firegreat123** [comment]
* Thanks. I will try to reconstruct these two files.
