### ISSUE TITLE
I use the synthesize datas  to train lenet，just achieve 12% accuracy

### ISSUE THREAD

**Issue by nene123456** [SsnL/dataset-distillation#4]
the dataset is mnist， I use random unknown initialization learned 100 synthetic data, then, i use 100 synthetic data to train a random initialization lenet，the accuracy just achieve 12%.
Maybe my code is wrong, can you release the code for me?

**Comment by SsnL** [comment]
Hi, code in this repo is our released version. What command did you use?

**Comment by nene123456** [comment]
python main.py --mode distill_basic --dataset MNIST --arch LeNet

**Comment by SsnL** [comment]
How did you evaluate the images? Could you post a output as a gist? Thanks!

**Comment by SsnL** [comment]
Close due to inactivity.  Feel free to reopen when you have more information to share.
