### ISSUE TITLE
Question about pulling data from a .gz file

### ISSUE THREAD

**Issue by kjurczyk** [SsnL/dataset-distillation#40]
Hello!

We are trying to use dataset distillation with a .gz file (similar to those that can be downloaded from the MNIST dataset). We've been looking through your dataset distillation code but we've been unable to find out where we could edit the code to pull data from our .gz file instead of from the MNIST dataset.

Could you please let me know in which file/line we could edit your dataset distillation code to pull data from the .gz file?

Thank you in advance!

**Comment by SsnL** [comment]
You need to add a new dataset class that can be created in https://github.com/SsnL/dataset-distillation/blob/24e6958cf23bc98de20a7b2714fc76fa7d38b874/datasets/__init__.py#L82 and corresponding entries to the `dataset_*` constants in https://github.com/SsnL/dataset-distillation/blob/master/datasets/__init__.py.

**Comment by hetingjane** [comment]
> You need to add a new dataset class that can be created in
> 
> https://github.com/SsnL/dataset-distillation/blob/24e6958cf23bc98de20a7b2714fc76fa7d38b874/datasets/__init__.py#L82
> 
> and corresponding entries to the `dataset_*` constants in https://github.com/SsnL/dataset-distillation/blob/master/datasets/__init__.py.

Thank you for answering my teammate's question! We appreciate it!
