### ISSUE TITLE
Adapt distill on dataset SVHN

### ISSUE THREAD

**Issue by Firegreat123** [SsnL/dataset-distillation#45]
* Hi, I have just train some networks of Lenet on Mnist and adapt distill on dataset USPS. I am wondering how can I adapt distill on dataset SVHN.

**Comment by SsnL** [comment]
Other than using the `mnist_rgb` variant (which has 3 channels instead of 1), it should be the same procedure as described at https://github.com/SsnL/dataset-distillation/blob/master/docs/advanced.md#adaptation-setting

**Comment by Firegreat123** [comment]
* Thank you. Really appreciate.
