### ISSUE TITLE
Question about commands

### ISSUE THREAD

**Issue by Firegreat123** [SsnL/dataset-distillation#47]
![image](https://user-images.githubusercontent.com/103976695/167237114-f30eb8ca-8ec2-4ad3-91c6-3afde996dc97.png)
* Hi, I can understand that 200 lenet networks are trained for distilling images. But what can those 20 test networks do?

**Comment by SsnL** [comment]
For testing the distilled images.

**Comment by Firegreat123** [comment]
* Thank you. Is that mean use these 20 networks training with distilled images?

**Comment by SsnL** [comment]
It’s just training networks on real images and store the weights, so that
they can be used for testing distilled images in adapt and forget settings.
This command does not yet do the testing distilled images part.

**Comment by Firegreat123** [comment]
* Thank you. Will the distilled images be used to train networks in testing part?

**Comment by SsnL** [comment]
see here for testing https://github.com/SsnL/dataset-distillation/blob/master/docs/advanced.md#testing
