### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by shraddha291996** [ssnl/dataset-distillation#56]
Hi, 
Im trying to run default options designed for random initializations one with on MINST with the following 

python main.py --mode distill_basic --dataset MNIST --arch LeNet 

and I get the error : AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

do you have any idea how I can fix this?  I have pytorch-gpu version 2.17 installed and conda version 22.9.0
Thank you

**Comment by ssnl** [comment]
It looks that you have a problem with your PyTorch installation. This is not in the scope of this repo. Sorry that we can't help further.

**Comment by shraddha291996** [comment]
> It looks that you have a problem with your PyTorch installation. This is not in the scope of this repo. Sorry that we can't help further.

okay, Thank you for the quick response
