### ISSUE TITLE
How the custom dataset be structured ?

### ISSUE THREAD

**Issue by shraddha291996** [ssnl/dataset-distillation#57]
Hello, Thank you for your great work.

Im new in this and I want to use distillation on my custom dataset but I am confused on how my dataset to be structured (or in which format) to use your network. Just as information my dataset is not large it has 100 images or so.

Thanks in advance

**Comment by ssnl** [comment]
The dataset format is just generic pytorch dataset, where each `__getitem__` gives you `(sample, label)`. See https://github.com/ssnl/dataset-distillation/issues/39 for more information.
