### ISSUE TITLE
'TestRunner' referenced before assignment

### ISSUE THREAD

**Issue by carmocca** [SsnL/dataset-distillation#6]
To compute the baseline for non-optimized random real images, I'm using the following command:
```bash
python main.py --dataset MNIST --arch LeNet \
    --distilled_images_per_class_per_step 10 \
    --phase test \
    --test_nets_type unknown_init \
    --test_distilled_images random_train \
    --test_n_nets 200 \
    --test_n_runs 10
```
however, I get the following error:
```
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    main(options.get_state())
  File "main.py", line 359, in main
    test_runner = TestRunner(state)
UnboundLocalError: local variable 'TestRunner' referenced before assignment
```
After taking a look, this seems to happen because `test_optimize_n_runs` is not set even though its supposed to be optional.

My guess is that https://github.com/SsnL/dataset-distillation/blob/master/main.py#L324-L355 should be out of its containing `else` block. Is that it or am I missing something?

Thank you.

**Comment by SsnL** [comment]
Yes, you are correct. Sorry about it. I have fixed in https://github.com/SsnL/dataset-distillation/commit/374298c9e9b3a00d79ce868daa7778611d1d2dc5
