### ISSUE TITLE
Possible bugs

### ISSUE THREAD

**Issue by hailuu684** [ssnl/dataset-distillation#61]
Hello,
I am testing your repo and I got this error. I am not sure if this is an issue in different torch versions or incompatibilities.

 I got an error in d.grad.add_(g). It says 'NoneType' object has no attribute 'add_'. I printed the type of 'd', it is obviously a Tensor type. I do not understand why can cause this problem.
![image](https://github.com/ssnl/dataset-distillation/assets/73364788/2f4eb811-348f-4be2-acd4-b28cda5573eb)

**Comment by hailuu684** [comment]
May I ask a question? I am curious about if I can use the generated distilled dataset that you already published to train with normal procedure. What I meant by the normal procedure is like the image below. Or do I have to write the customized network as you did?

![image](https://github.com/ssnl/dataset-distillation/assets/73364788/7d9aa544-5bc7-494e-b963-62fbef8dc1db)

**Comment by hailuu684** [comment]
Thank you for your quick reply, I haven't modified the code but still got this error. Can you suggest where should I take a look on? Honestly, your code is advanced to me.

![image](https://github.com/ssnl/dataset-distillation/assets/73364788/e98e3754-b52c-40a6-9abd-830fd6b8f5dc)

**Comment by ssnl** [comment]
It might be a torch version issue then because I didn't see this before. I guess you can try to change code to test 
+ if `d.grad is None`, just `g` assign to `d.grad`
+ otherwise, add `g` to it.

Although I haven't experienced the error you are seeing so I can't guarantee correctness.

**Comment by hailuu684** [comment]
Thank you for the instruction, here is the updated code for anyone who is having the same error like me

![image](https://github.com/ssnl/dataset-distillation/assets/73364788/261bb437-d070-4a50-917e-bd677f24fee2)

**Comment by hailuu684** [comment]
May I ask this question? In your code, are you using real data to generate distilled dataset? and then training on the distilled dataset? However, in the function init_data_optim, I see distill_label and distill_data are generating randomly. I understand that this is the initialization, but in which part of your code updates the distilled data? would you mind if you could point it out for me? Thank you very much.

![image](https://github.com/ssnl/dataset-distillation/assets/73364788/e5a33627-dea8-4ebe-98b5-47aadd2b8972)

**Comment by ssnl** [comment]
@hailuu684 In this code, distilled data are initialized as random noise. But yes, many works show that initializing from real images can work better in certain cases. It is not implemented here.
