### ISSUE TITLE
Train fails on each and every command

### ISSUE THREAD

**Issue by gonenraveh** [ssnl/dataset-distillation#62]
Hi

I ran:
python main.py --mode distill_basic --dataset Cifar10 --arch AlexCifarNet     --distill_lr 0.001 --train_nets_type known_init --n_nets 1     --test_nets_type same_as_trai

and got:
 File "cifar_100_dataset_distillation/dataset-distillation/train_distilled_image.py", line 176, in accumulate_grad
    d.grad.add_(g)
AttributeError: 'NoneType' object has no attribute 'add_'

Please advise.
Gonen

**Comment by ssnl** [comment]
We haven't tested this code on later pytorch versions. If you see problems, please try using pytorch 1.0.0.
