### ISSUE TITLE
Bug in kmeans baseline function?

### ISSUE THREAD

**Issue by carmocca** [SsnL/dataset-distillation#9]
After running the function to extract the kmeans centroids as baselines, I saved some of these centroids as png images and noticed some of them look like noise which might suggest the presence of a bug, however, I haven't gone through the code myself.

Here are a few of the centroids generated for MNIST class 3:
![30](https://user-images.githubusercontent.com/11067892/54505948-77e5f200-493a-11e9-85da-3c096bd247b7.png)![31](https://user-images.githubusercontent.com/11067892/54505949-77e5f200-493a-11e9-93e3-9207347603f5.png)![32](https://user-images.githubusercontent.com/11067892/54505950-787e8880-493a-11e9-939a-5853a5c111a0.png)![33](https://user-images.githubusercontent.com/11067892/54505951-787e8880-493a-11e9-9dc5-28705fb96ab4.png)![34](https://user-images.githubusercontent.com/11067892/54505952-787e8880-493a-11e9-9756-869d2db18e67.png)![35](https://user-images.githubusercontent.com/11067892/54505954-787e8880-493a-11e9-8c44-13ca6375acc5.png)![36](https://user-images.githubusercontent.com/11067892/54505956-79171f00-493a-11e9-84a9-7ac17c60b5e2.png)![37](https://user-images.githubusercontent.com/11067892/54505957-79171f00-493a-11e9-9f56-bbdd53430a12.png)![38](https://user-images.githubusercontent.com/11067892/54505958-79171f00-493a-11e9-9692-b2243cd57f3a.png)![39](https://user-images.githubusercontent.com/11067892/54505959-79afb580-493a-11e9-84d9-cb913ffee045.png)

Any idea of what might be the cause? If it is an actual bug I guess this would impact the values presented in the paper.

For reference, here is the code I used:

```python
data = dataset_distillation.utils.baselines.kmeans_train(state, p=2)
imgs, labels = data[-1]  # Use last step
for i, img in enumerate(imgs):
    torchvision.utils.save_image(img, f"{i}.png", nrow=1, padding=0)
```

Thank you.

**Comment by SsnL** [comment]
Thanks for pointing this out. It is possible that some centers didn't have data assigned to them. I initialized the cluster centers as random noise, but I should have done a cleverer initialization scheme like kmeans++.

**Comment by SsnL** [comment]
Fixed in https://github.com/SsnL/dataset-distillation/commit/3837bc2b2808a04a99f26a6e71261789f45b43a8. arXiv will be updated soon.
